CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  user_name VARCHAR(255) NOT NULL,
  initiator_rating FLOAT4 CHECK (initiator_rating > 0 AND initiator_rating < 11)
);

CREATE TABLE IF NOT EXISTS categories (
  category_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
  event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT NOT NULL REFERENCES categories (category_id),
  confirmed_requests BIGINT NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_created TIMESTAMP NOT NULL,
  event_date_start TIMESTAMP NOT NULL,
  event_date_end TIMESTAMP NOT NULL,
  event_status VARCHAR(16) NOT NULL CHECK(event_status IN ('CANCELED', 'PENDING', 'PUBLISHED')),
  event_title VARCHAR(120) NOT NULL,
  initiator_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
  location_latitude FLOAT4 NOT NULL,
  location_longitude FLOAT4 NOT NULL,
  paid BOOLEAN NOT NULL,
  participant_limit INTEGER NOT NULL,
  published TIMESTAMP,
  request_moderation BOOLEAN NOT NULL,
  views BIGINT NOT NULL,
  event_rating FLOAT4 CHECK (event_rating > 0 AND event_rating <= 10),
  part_of_voted FLOAT4 CHECK (part_of_voted > 0 AND part_of_voted <= 1)
);

CREATE TABLE IF NOT EXISTS compilations (
  compilation_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compilation_title VARCHAR(120) NOT NULL,
  pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS event_compilation (
  event_id BIGINT NOT NULL REFERENCES events (event_id) ON DELETE CASCADE,
  compilation_id BIGINT NOT NULL REFERENCES compilations (compilation_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
  request_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events (event_id) ON DELETE CASCADE,
  request_created TIMESTAMP NOT NULL,
  request_status VARCHAR(16) NOT NULL CHECK(request_status IN ('CANCELED', 'CONFIRMED', 'PENDING', 'REJECTED')),
  requester_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
  rating_from_requester INTEGER CHECK (rating_from_requester > 0 AND requests.rating_from_requester < 11)
);





	
	
	
	
	
