version: '3.1'
services:
  stats-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db
    volumes:
      - stats-db:/var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  stats-server:
    build: ./stat-service
    container_name: ewm-stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=ewm-stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    volumes:
      - ewm-db:/var/lib/postgresql/data
    ports:
      - "6540:5432"
    depends_on:
      - stats-db
      - stats-server
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main

  ewm-service:
    build: ./main-service
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - stats-db
      - stats-server
      - ewm-db
    environment:
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm-main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
      - ewm-stat-server.url=http://stats-server:9090

volumes:
  ewm-db:
  stats-db: