version: '3.1'
services:
  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:13.7-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
      build: ./stat-service
      container_name: ewm-stat-server
      ports:
        - "9090:9090"
      depends_on:
        - ewm-service
      environment:
        - DB_HOST=db
        - DB_PORT=5432
        - DB_NAME=ewm-stats
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root